### ISSUE TITLE
Meta issue: Features of the app

### ISSUE THREAD

**Issue by volcwolf** [volcwolf/Metazooa-Helper#1]
- [ ] Serve the list of animals
- [ ] Have a wiki link next to each of the animals
- [ ] make animals clickable (once to strike through and twice to cancel strike through)
- [ ] Find a way to collect taxonomical animal data
- [ ] Link each animal in list to relevant taxonomical data
- [ ] search function related to relevant taxon keywords (highlight or filter based on keywords)
- [ ] mass strikeout via search function
